name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{'Siddharth-M-77'}}
          outputs: dist/snake.svg

      - name: Push Generated Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated snake animation"
          add: "dist/snake.svg"
